Made changes to only allow a valid IPv4 or Ipv6 string for dhcp cli (#2296)
What I did
Currently,

root@qa-eth-vt04-3-2700a0:/home/admin# config vlan dhcp_relay add 125 11
Added DHCP relay destination address 11 to Vlan125
Restarting DHCP relay service...
root@qa-eth-vt04-3-2700a0:/home/admin# config vlan dhcp_relay add 125 1100000
Added DHCP relay destination address 1100000 to Vlan125
Restarting DHCP relay service...
root@qa-eth-vt04-3-2700a0:/home/admin# show vla bri
+-----------+--------------+-----------+----------------+-----------------------+-------------+
|   VLAN ID | IP Address   | Ports     | Port Tagging   | DHCP Helper Address   | Proxy ARP   |
+===========+==============+===========+================+=======================+=============+
|       125 | 2000::1:1/64 | Ethernet4 | tagged         | 500                   | disabled    |
|           |              |           |                | 11                    |             |
|           |              |           |                | 1100000               |             |
|           |              |           |                | 2000:1::2             |             |
+-----------+--------------+-----------+----------------+-----------------------+-------------+
Made changes to take in a valid IP string.

After the change:

root@qa-eth-vt02-7-3420:/home/admin# config vlan dhcp_relay add 125 1100000
Error: 1100000 is invalid IP address

Signed-off-by: Vivek Reddy vkarri@nvidia.com